version: '3.7'

services:
  app:
    container_name: app
    build: ./backend
    command: |
      bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000'
    volumes:
      - ./backend/:/app/
    ports:
      - 80:8000
    environment:
      - DATABASE_URI=postgresql://testuser:password@db/backend_db
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: db
    volumes:
      - ./data/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=backend_db


  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - app

volumes: 
    data: 